version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16.x 
    commands:
      - echo Installing NPM dependencies...
      - npm install
      - echo Installed NPM dependencies...
  build:
    commands:
      - echo Staging build started on `date`
      - npm run build
      - echo Staging build completed on `date`
artifacts:
  files:
    - '**/*' 
  base-directory: 'build'
cache:
  paths:
    - node_modules/**/*